config/routes.rb
Rails.application.routes.draw do
  resources :bar_codes
  resources :weight_calculators
  resources :employee_productivities 
  
  get 'productivity', to: 'employee_productivities#index'
  
  resources :charts do
    get :download_report
  end
  resources :trackers

  scope :ujs, defaults: { format: :ujs } do
    patch 'wt_totals' => 'weight_calculators#totals'
    patch 'thing_totals' => 'trackers#totals'
  end

  post 'search' => 'trackers#search'
  resources :import  do
    collection do
      post :import
      post :parts
    end
  end
  resources :iot_data do
    # get  'process_start' => 'iot_data#process_start'
    # match '/process_start' => 'iot_data#process_start', via: :post
    # match '/request' => 'iot_data#process_start', via: :get
    # member do
      get :process_start
      get :download_report
      # get :print_pdf
    # end
    collection do
      post :import
    end
  end
  devise_for :users
  # devise_for :users, only: :session, path: 'session',
  #            path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users, only: [:show]
  
  root to: 'visitors#index'
  # root to: 'iot_data#index'
end

app/models/bar_code.rb
class BarCode < ActiveRecord::Base
end

app/controllers/bar_codes_controller.rb
class BarCodesController < ApplicationController
  before_action :set_bar_code, only: [:show, :edit, :update, :destroy]

  # GET /bar_codes
  # GET /bar_codes.json
  def index
    @bar_codes = BarCode.all
  end

  # GET /bar_codes/1
  # GET /bar_codes/1.json
  def show
  end

  # GET /bar_codes/new
  def new
    @bar_code = BarCode.new
  end

  # GET /bar_codes/1/edit
  def edit
  end

  # POST /bar_codes
  # POST /bar_codes.json
  def create
    @bar_code = BarCode.new(bar_code_params)

    respond_to do |format|
      if @bar_code.save
        format.html { redirect_to @bar_code, notice: 'Bar code was successfully created.' }
        format.json { render :show, status: :created, location: @bar_code }
      else
        format.html { render :new }
        format.json { render json: @bar_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bar_codes/1
  # PATCH/PUT /bar_codes/1.json
  def update
    respond_to do |format|
      if @bar_code.update(bar_code_params)
        format.html { redirect_to @bar_code, notice: 'Bar code was successfully updated.' }
        format.json { render :show, status: :ok, location: @bar_code }
      else
        format.html { render :edit }
        format.json { render json: @bar_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bar_codes/1
  # DELETE /bar_codes/1.json
  def destroy
    @bar_code.destroy
    respond_to do |format|
      format.html { redirect_to bar_codes_url, notice: 'Bar code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bar_code
      @bar_code = BarCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bar_code_params
      params.require(:bar_code).permit(:asn, :part_code, :qty, :date, :lot_size, :target, :location)
    end
end

app/helpers/bar_codes_helper.rb
module BarCodesHelper
end

app/views/bar_codes/_form.html.erb
<%= form_for(@bar_code) do |f| %>
  <% if @bar_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar_code.errors.count, "error") %> prohibited this bar_code from being saved:</h2>

      <ul>
      <% @bar_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asn %><br>
    <%= f.text_field :asn %>
  </div>
  <div class="field">
    <%= f.label :part_code %><br>
    <%= f.text_field :part_code %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.number_field :qty %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :lot_size %><br>
    <%= f.number_field :lot_size %>
  </div>
  <div class="field">
    <%= f.label :target %><br>
    <%= f.number_field :target %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bar_codes/edit.html.erb
<h1>Editing Bar Code</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar_code %> |
<%= link_to 'Back', bar_codes_path %>

app/views/bar_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bar Codes</h1>

<table>
  <thead>
    <tr>
      <th>Asn</th>
      <th>Part code</th>
      <th>Qty</th>
      <th>Date</th>
      <th>Lot size</th>
      <th>Target</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bar_codes.each do |bar_code| %>
      <tr>
        <td><%= bar_code.asn %></td>
        <td><%= bar_code.part_code %></td>
        <td><%= bar_code.qty %></td>
        <td><%= bar_code.date %></td>
        <td><%= bar_code.lot_size %></td>
        <td><%= bar_code.target %></td>
        <td><%= bar_code.location %></td>
        <td><%= link_to 'Show', bar_code %></td>
        <td><%= link_to 'Edit', edit_bar_code_path(bar_code) %></td>
        <td><%= link_to 'Destroy', bar_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bar code', new_bar_code_path %>

app/views/bar_codes/new.html.erb
<h1>New Bar Code</h1>

<%= render 'form' %>

<%= link_to 'Back', bar_codes_path %>

app/views/bar_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asn:</strong>
  <%= @bar_code.asn %>
</p>

<p>
  <strong>Part code:</strong>
  <%= @bar_code.part_code %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @bar_code.qty %>
</p>

<p>
  <strong>Date:</strong>
  <%= @bar_code.date %>
</p>

<p>
  <strong>Lot size:</strong>
  <%= @bar_code.lot_size %>
</p>

<p>
  <strong>Target:</strong>
  <%= @bar_code.target %>
</p>

<p>
  <strong>Location:</strong>
  <%= @bar_code.location %>
</p>

<%= link_to 'Edit', edit_bar_code_path(@bar_code) %> |
<%= link_to 'Back', bar_codes_path %>