config/routes.rb
Rails.application.routes.draw do
  resources :bar_codes
  resources :weight_calculators
  resources :employee_productivities 
  
  get 'productivity', to: 'employee_productivities#index'
  
  resources :charts do
    get :download_report
  end
  resources :trackers

  scope :ujs, defaults: { format: :ujs } do
    patch 'wt_totals' => 'weight_calculators#totals'
    patch 'thing_totals' => 'trackers#totals'
  end

  post 'search' => 'trackers#search'
  resources :import  do
    collection do
      post :import
      post :parts
    end
  end
  resources :iot_data do
    # get  'process_start' => 'iot_data#process_start'
    # match '/process_start' => 'iot_data#process_start', via: :post
    # match '/request' => 'iot_data#process_start', via: :get
    # member do
      get :process_start
      get :download_report
      # get :print_pdf
    # end
    collection do
      post :import
    end
  end
  devise_for :users
  # devise_for :users, only: :session, path: 'session',
  #            path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :users, only: [:show]
  
  root to: 'visitors#index'
  # root to: 'iot_data#index'
end

app/models/employee_productivity.rb
class EmployeeProductivity < ActiveRecord::Base
end

app/controllers/employee_productivities_controller.rb
class EmployeeProductivitiesController < ApplicationController
  layout "iems"
  skip_before_filter :authenticate_user!
  before_action :set_employee_productivity, only: [:show, :edit, :update, :destroy]

  # GET /employee_productivities
  # GET /employee_productivities.json
  def index
    @employee_productivities = EmployeeProductivity.all

    device_id = params[:device_id]
    device_active = params[:device_active]
    axis_data = params[:axis_data]
    emp_activity = params[:emp_activity]
    idle = params[:idle]
    pick = params[:pick]

    @ep_data = EmployeeProductivity.where("device_id = ? and device_active = ? and axis_data = ? and emp_activity = ? and idle = ? and pick = ?", device_id, device_active, axis_data, emp_activity, idle, pick) if device_id && device_active && axis_data && emp_activity && idle && pick
    puts @ep_data.inspect

    if device_id != nil
      @iems_data = EmployeeProductivity.new
      @iems_data.device_id = device_id
      @iems_data.device_active = device_active
      @iems_data.axis_data = axis_data
      @iems_data.emp_activity = emp_activity
      @iems_data.idle = idle
      @iems_data.pick = pick
      @iems_data.save!
    end  
  end

  # GET /employee_productivities/1
  # GET /employee_productivities/1.json
  def show
  end

  # GET /employee_productivities/new
  def new
    @employee_productivity = EmployeeProductivity.new
  end

  # GET /employee_productivities/1/edit
  def edit
  end

  # POST /employee_productivities
  # POST /employee_productivities.json
  def create
    @employee_productivity = EmployeeProductivity.new(employee_productivity_params)

    respond_to do |format|
      if @employee_productivity.save
        format.html { redirect_to @employee_productivity, notice: 'Employee productivity was successfully created.' }
        format.json { render :show, status: :created, location: @employee_productivity }
      else
        format.html { render :new }
        format.json { render json: @employee_productivity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_productivities/1
  # PATCH/PUT /employee_productivities/1.json
  def update
    respond_to do |format|
      if @employee_productivity.update(employee_productivity_params)
        format.html { redirect_to @employee_productivity, notice: 'Employee productivity was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_productivity }
      else
        format.html { render :edit }
        format.json { render json: @employee_productivity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_productivities/1
  # DELETE /employee_productivities/1.json
  def destroy
    @employee_productivity.destroy
    respond_to do |format|
      format.html { redirect_to employee_productivities_url, notice: 'Employee productivity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_productivity
      @employee_productivity = EmployeeProductivity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_productivity_params
      params.require(:employee_productivity).permit(:device_id, :device_active, :axis_data, :emp_activity, :idle, :pick)
    end
end

app/helpers/employee_productivities_helper.rb
module EmployeeProductivitiesHelper
end

app/views/employee_productivities/_form.html.erb
<%= form_for(@employee_productivity) do |f| %>
  <% if @employee_productivity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee_productivity.errors.count, "error") %> prohibited this employee_productivity from being saved:</h2>

      <ul>
      <% @employee_productivity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.number_field :device_id %>
  </div>
  <div class="field">
    <%= f.label :device_active %><br>
    <%= f.text_field :device_active %>
  </div>
  <div class="field">
    <%= f.label :axis_data %><br>
    <%= f.text_field :axis_data %>
  </div>
  <div class="field">
    <%= f.label :emp_activity %><br>
    <%= f.text_field :emp_activity %>
  </div>
  <div class="field">
    <%= f.label :idle %><br>
    <%= f.text_field :idle %>
  </div>
  <div class="field">
    <%= f.label :pick %><br>
    <%= f.text_field :pick %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employee_productivities/edit.html.erb
<h1>Editing Employee Productivity</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee_productivity %> |
<%= link_to 'Back', employee_productivities_path %>

app/views/employee_productivities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employee Productivities</h1>

<table>
  <thead>
    <tr>
      <th>Device</th>
      <th>Device active</th>
      <th>Axis data</th>
      <th>Emp activity</th>
      <th>Idle</th>
      <th>Pick</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_productivities.each do |employee_productivity| %>
      <tr>
        <td><%= employee_productivity.device_id %></td>
        <td><%= employee_productivity.device_active %></td>
        <td><%= employee_productivity.axis_data %></td>
        <td><%= employee_productivity.emp_activity %></td>
        <td><%= employee_productivity.idle %></td>
        <td><%= employee_productivity.pick %></td>
        <td><%= link_to 'Show', employee_productivity %></td>
        <td><%= link_to 'Edit', edit_employee_productivity_path(employee_productivity) %></td>
        <td><%= link_to 'Destroy', employee_productivity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee productivity', new_employee_productivity_path %>

app/views/employee_productivities/new.html.erb
<h1>New Employee Productivity</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_productivities_path %>

app/views/employee_productivities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @employee_productivity.device_id %>
</p>

<p>
  <strong>Device active:</strong>
  <%= @employee_productivity.device_active %>
</p>

<p>
  <strong>Axis data:</strong>
  <%= @employee_productivity.axis_data %>
</p>

<p>
  <strong>Emp activity:</strong>
  <%= @employee_productivity.emp_activity %>
</p>

<p>
  <strong>Idle:</strong>
  <%= @employee_productivity.idle %>
</p>

<p>
  <strong>Pick:</strong>
  <%= @employee_productivity.pick %>
</p>

<%= link_to 'Edit', edit_employee_productivity_path(@employee_productivity) %> |
<%= link_to 'Back', employee_productivities_path %>